name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Show deno version
        run: deno --version
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
